<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>LGA_WinSetFTA</AssemblyName>
    <RootNamespace>DefaultApps</RootNamespace>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Resources\LookUpLut4.bin" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
